module.exports={
    USER_COLLECTION:'users',
    ADMIN_COLLECTION:'admin',
    PRODUCT_COLLECTION:'product',
    BANNER_COLLECTION:'banner',
    BRAND_COLLECTION:'brand',
    BANNER_1:'banner1',
    BANNER_2:'banner2',
    BANNER_3:'banner3',
    BANNER_4:'banner4',
    CART_COLLECTION:'cart'
}